### ISSUE TITLE
Подсветка вопросов при наведении в блоке последних вопросов

### ISSUE THREAD

**Issue by ghost** [Niklan/Dru.io#94]
Думаю будет удобнее если в блоке "последние вопросы" сделать подсветку вопроса при наведении мышки. что то типа 

``` css
.last_questions .question:hover {
    background: #eee; \\ Цвет выбран для примера.
}
```
